name: Build NetMotive IP Switcher

on:
  push:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller psutil

      - name: Build EXE with icon
        run: |
          pyinstaller --onefile --windowed --add-data "icon.ico;." netmotive_ip_switcher.py

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: NetMotive-IP-Switcher-EXE
          path: dist/netmotive_ip_switcher.exe

  build_macos:                # ✅ valid ID
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyinstaller psutil

      - name: Build macOS binary
        run: pyinstaller --onefile --windowed --add-data "profiles.json:." network_profile_switcher.py

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: NetworkProfileSwitcher-macOS
          path: dist/network_profile_switcher
