name: Build & Package Network Profile Switcher
on:
  push:
    branches: [ main ]     # every push to main triggers the build

jobs:
  build‑windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyinstaller psutil

      - name: Build Windows EXE
        # one‑line command avoids the PowerShell ^ issue
        run: pyinstaller --onefile --noconsole --add-data "profiles.json;." network_profile_switcher.py

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: NetworkProfileSwitcher-Windows
          path: dist/network_profile_switcher.exe

  build‑macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyinstaller psutil

      - name: Build macOS binary
        run: pyinstaller --onefile --windowed --add-data "profiles.json:." network_profile_switcher.py

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: NetworkProfileSwitcher-macOS
          path: dist/network_profile_switcher
